CREATE DATABASE IF NOT EXISTS LeaveRequestDB
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE LeaveRequestDB;

CREATE TABLE DEPARTMENTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    STATUS INT NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_CODE VARCHAR(20) NOT NULL UNIQUE,
    FULL_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(255),
    POSITION VARCHAR(100),
    DEPARTMENT_ID BIGINT,
    ROLE INT NOT NULL,
    STATUS INT NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_USERS_DEPARTMENTS
        FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENTS(ID)
);

CREATE TABLE LEAVE_TYPES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(500),
    STATUS INT NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LEAVE_REQUESTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    REQUEST_CODE VARCHAR(20) NOT NULL UNIQUE,
    EMPLOYEE_ID BIGINT NOT NULL,
    LEAVE_TYPE_ID BIGINT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    NUMBER_OF_DAYS DECIMAL(5,1) NOT NULL,
    REASON VARCHAR(1000) NOT NULL,
    NOTE VARCHAR(500),
    HANDOVER_PERSON VARCHAR(100),
    STATUS INT NOT NULL DEFAULT 1,
    MANAGER_ID BIGINT,
    MANAGER_RESPONSE VARCHAR(1000),
    PROCESSED_AT DATETIME,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_REQUESTS_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES USERS(ID),

    CONSTRAINT FK_REQUESTS_LEAVE_TYPE
        FOREIGN KEY (LEAVE_TYPE_ID)
        REFERENCES LEAVE_TYPES(ID),

    CONSTRAINT FK_REQUESTS_MANAGER
        FOREIGN KEY (MANAGER_ID)
        REFERENCES USERS(ID)
);
// thêm mặc định phòng ban
select * from DEPARTMENTS

INSERT INTO DEPARTMENTS (CODE, NAME, STATUS)
VALUES
('IT', 'Phòng Công nghệ thông tin', 1),
('HR', 'Phòng Nhân sự', 1),
('ACC', 'Phòng Kế toán', 1),
('MKT', 'Phòng Marketing', 1),
('SALE', 'Phòng Kinh doanh', 1);